// <auto-generated />
namespace LM.WpfClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial_commit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_commit));
        
        string IMigrationMetadata.Id
        {
            get { return "201410011228475_initial_commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
